spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpabook
    username: jpabook_admin
    password: jpashop
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true # system out , 주석은 command + /, 운영환경에서는 사용하면 안 됨
        format_sql: true

logging:
  level:
    org.springframework: info
    org.hibernate.SQL: info # logger
